use_frameworks!

platform :ios, '10.0'

target 'JUNTableView_Example' do
  pod 'JUNTableView', :path => '../'

  target 'JUNTableView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
